[context.deploy-preview.environment]
  HUGO_VERSION = "0.72.0"


[context.production.environment]
   HUGO_VERSION = "0.72.0"

[build]
  publish = "public"
  command = "git submodule update --init --recursive && hugo"